import { useState } from "react";

export default function App() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const handleFile = (e) => setFile(e.target.files[0]);

  const handleUpload = async () => {
    if (!file) return alert("Please choose a PDF file first");
    setLoading(true);
    setError(null);
    setResult(null);
    const form = new FormData();
    form.append("file", file);

    try {
      const res = await fetch("http://localhost:8000/generate", {
        method: "POST",
        body: form,
      });
      if (!res.ok) {
        const txt = await res.text();
        throw new Error(txt || "Server error");
      }
      const json = await res.json();
      setResult(json);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: 20, fontFamily: "sans-serif", maxWidth: 800 }}>
      <h2>Paper → Abstract</h2>
      <p>
        Upload a PDF and get an abstract generated by your fine-tuned LED model.
      </p>

      <input type="file" accept="application/pdf" onChange={handleFile} />
      <div style={{ marginTop: 12 }}>
        <button onClick={handleUpload} disabled={loading}>
          Generate Abstract
        </button>
      </div>

      {loading && <p>Generating... this may take a while for long papers.</p>}
      {error && <p style={{ color: "red" }}>Error: {error}</p>}
      {result && (
        <div style={{ marginTop: 20 }}>
          <h3>Abstract (generated)</h3>
          <p
            style={{
              whiteSpace: "pre-wrap",
              background: "#f6f6f6",
              padding: 12,
            }}
          >
            {result.abstract}
          </p>
          <small>Chunks processed: {result.chunks}</small>
        </div>
      )}
    </div>
  );
}
